apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-storage
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostpath: 
    path: "/mnt/grafana"